---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    name: nginx-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nginx-dep
  template:
    metadata:
      labels:
        name: nginx-dep
    spec:
      containers:
        - name: nginx-dep
          image: nginx:latest
          ports:
            - name: http
              containerPort: 80
              protocol: TCP

          resources:
            requests:
              memory: '256Mi'
              cpu: '500m'

            limits:
              memory: '512Mi'
              cpu: '700m'

          livenessProbe:
            httpGet:
              path: /heath
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /ready
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment
  labels:
    name: nginx-dep
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
  selector:
    name: nginx-dep


#for detail understanding please visit description.txt
